# Generated by Django 4.0.4 on 2022-05-12 20:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('news_id', models.PositiveBigIntegerField(unique=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255)),
                ('time', models.PositiveBigIntegerField(default=1652388817.783239, null=True)),
                ('dead', models.BooleanField(blank=True, default=False, null=True)),
                ('kids', models.JSONField(blank=True, default=list, null=True)),
                ('descendants', models.PositiveBigIntegerField(null=True)),
                ('score', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(null=True)),
                ('is_hackernews', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_id', models.PositiveBigIntegerField(unique=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=255)),
                ('time', models.PositiveBigIntegerField(default=1652388817.783239, null=True)),
                ('dead', models.BooleanField(blank=True, default=False, null=True)),
                ('kids', models.JSONField(blank=True, default=list, null=True)),
                ('parent', models.BigIntegerField(null=True)),
                ('text', models.TextField(null=True)),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.story')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
