# Generated by Django 3.2.13 on 2022-05-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='news',
            new_name='story',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='news_id',
            new_name='story_id',
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.PositiveBigIntegerField(default=1652487053.200346, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.PositiveBigIntegerField(default=1652487053.200346, null=True),
        ),
    ]
